name: cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  excel: 2.0.0-null-safety-3
  # get: 4.6.5
  change_case: ^1.0.0+3
  supabase: 1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
